# Generated by Django 3.1.4 on 2020-12-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='update_data',
            new_name='update_date',
        ),
    ]
